// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAVuBJPPT_6RjEOCY-UT-ZF8Wj3VWD2VeY',
    appId: '1:230651499148:web:21abdaa0372378045e21a9',
    messagingSenderId: '230651499148',
    projectId: 'hellofa-d76cc',
    authDomain: 'hellofa-d76cc.firebaseapp.com',
    storageBucket: 'hellofa-d76cc.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCOuEIQTbyUEL7mlzJNy4GSgp0qu7dzgDA',
    appId: '1:230651499148:android:e9808ba4ff373c895e21a9',
    messagingSenderId: '230651499148',
    projectId: 'hellofa-d76cc',
    storageBucket: 'hellofa-d76cc.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBt9OOs0zxEas71g92J926a4BWmD5PIdec',
    appId: '1:230651499148:ios:bda149c773c70b695e21a9',
    messagingSenderId: '230651499148',
    projectId: 'hellofa-d76cc',
    storageBucket: 'hellofa-d76cc.appspot.com',
    iosClientId: '230651499148-rkorhtgf1nsubm6rm92f83dgb3r13p2t.apps.googleusercontent.com',
    iosBundleId: 'com.example.helloMeal',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBt9OOs0zxEas71g92J926a4BWmD5PIdec',
    appId: '1:230651499148:ios:bda149c773c70b695e21a9',
    messagingSenderId: '230651499148',
    projectId: 'hellofa-d76cc',
    storageBucket: 'hellofa-d76cc.appspot.com',
    iosClientId: '230651499148-rkorhtgf1nsubm6rm92f83dgb3r13p2t.apps.googleusercontent.com',
    iosBundleId: 'com.example.helloMeal',
  );
}
